USE master
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'QLSieuThiDB')
BEGIN
    ALTER DATABASE QLSieuThiDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QLSieuThiDB;
END
GO

CREATE DATABASE QLSieuThiDB
GO

USE QLSieuThiDB
GO